### ISSUE TITLE
Add more examples to run on CI

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/pineappl#313] opened 2024-09-25 07:45 UTC
Triggered by [this comment](https://github.com/NNPDF/pineappl/pull/309#issuecomment-2366401276) I think it'd be indeed good to run the Python examples on the CI. Indeed, while running all of the examples, the Python ones broke which I fixed in #310. More Python examples should also be added.

**Comment by cschwan** [comment] 2024-09-25 08:08
The C, C++ and Fortran APIs are run, tested and code coverage is generated here: <https://github.com/NNPDF/pineappl/blob/master/.github/workflows/capi.yaml>. For the Python interface we should have more examples, [run and test them in the CI](https://github.com/NNPDF/pineappl/issues/108), of course.

**Comment by Radonirinaunimi** [comment] 2024-09-25 08:12
> The C, C++ and Fortran APIs are run, tested and code coverage is generated here: https://github.com/NNPDF/pineappl/blob/master/.github/workflows/capi.yaml. For the Python interface we should have more examples, [run and test them in the CI](https://github.com/NNPDF/pineappl/issues/108), of course.

Ah, yes! Then it is just about adding more Python examples and **also** run them on the CI.

**Comment by cschwan** [comment] 2024-09-25 08:51
Then I believe this is a duplicate of #108.

**Comment by Radonirinaunimi** [comment] 2024-09-25 08:53
I agree, I will implement this there.

**Closed** 2024-10-24 12:11 UTC
Labels: enhancement
