### ISSUE TITLE
Issue converting NNLO ttbar fastnlo grids

### ISSUE THREAD

**Issue by LucianHL** [NNPDF/pineappl#318] opened 2024-10-17 20:32 UTC
Hi,

I have run the fastnlo to pineappl converter without issue for NLO grids, but for the NNLO grids for ttbar production provided [here](https://www.precision.hep.phy.cam.ac.uk/results/ttbar-fastnlo/) there is a small but non-negligible difference between the original and converted grids. E.g. for `LHC8-Mtt-HT4-173_3-bin1.tab` from [here](http://www.precision.hep.phy.cam.ac.uk/wp-content/results/fastNLOtables/fastNLO-ttbar-NNLO-LHC8-173_3-bin1.tar.gz) I get:

```
b   PineAPPL     fastNLO      rel. diff
-+------------+------------+-------------
0  1.0817194e0  1.0821781e0  4.2405530e-4
1  1.0725099e0  1.0722009e0 -2.8814110e-4
2 6.5609663e-1 6.5619054e-1  1.4314243e-4
3 3.3629315e-1 3.3631982e-1  7.9301309e-5
4 1.3767895e-1 1.3750424e-1 -1.2689380e-3
5 3.4284160e-2 3.4298089e-2  4.0628058e-4
6 4.1848976e-3 4.1888985e-3  9.5603763e-4
```

which is not awful but a lot more than usual, and indeed it fails the default accuracy test. I don't think this is the same issue as in #228 as the scale is not flexible - and anyway the differences are too small for that. Perhaps this is due the grids being NNLO?

**Comment by cschwan** [comment] 2024-10-18 08:16
Hi @LucianHL,

I can reproduce the behaviour and that's definitely a bug. I don't think it's directly related to NNLO, as we have successfully converted other fastNLO tables A. Mitov's website.

**Comment by LucianHL** [comment] 2024-10-18 09:26
Hi @cschwan, thank you - yes indeed I was going to say that I had tried others and they had the same issue.

**Comment by cschwan** [comment] 2024-10-18 13:48
This was a genuine bug that was caused by having accidentally swapped the `x1` and `x2`, see commit 213e68a267aec611f0943de9ba16d1b6bd359aaa. This has now been fixed in `master` and `v0.8.x`.

**Comment by LucianHL** [comment] 2024-10-18 14:06
Hi @cschwan thank you yes that has worked!

**Comment by cschwan** [comment] 2024-10-18 14:26
No worries and thank you for the report, @LucianHL, this should've been discovered a long time ago!

**Closed by cschwan** 2024-10-18 14:26 UTC
Labels: bug

**Comment by felixhekhorn** [comment] 2024-10-21 07:36
> EDIT: I closed this with a comment but should probably leave that to do you to do in case there is more to be done here, so have re-opened

just for future reference: I would say the person who opens an issue should preferably also close it to confirm it is actually resolved. If further actions are required on our side we reopen it :upside_down_face: (and close again)
